Run `taskcat package`
`taskcat test run` has some issues, we'll tend to that later.

This task now does a couple of things:
- It uses a concourses cache to maintain docker image caching. Before
  the task actually runs, we check if there are images cached, and if
  so, we `docker load` them. After the task ran, all docker images are
  pulled via `docker save` and put into the concourse cache. Thus, next
  time the task runs, we have those images available, even though the VM
  `dockerd` runs on, is epehermal.
- `taskcat` builds a bunch of containers via Dockerfiles. Those have
  some `FROM` stanzas in it, which point to dockerhub. With dockerhub's
  ratelimiting, we might run into issues here. Thus, we try to get all
  images from those `FROM` stanzas, pull them in through a proxy-cache
  and then re-tag them with the original tag. Thus, nothing should
  really be pulled directly from dockerhub.

This is all still in-line, but will be broken out to distinct task files
& libraries as one of the next steps.

diff --git a/ci/qs-test/pipeline.yml b/ci/qs-test/pipeline.yml
--- a/ci/qs-test/pipeline.yml
+++ b/ci/qs-test/pipeline.yml
@@ -62,14 +62,14 @@ jobs:
     params:
       NIMBUS_USER: ((ci/nimbus.user))
       NIMBUS_DEPLOY_OPTS: '--cpus=4 --memory=4096'
-      DOCKER_USER: ((ci/registry/dockerhub/horlh.username))
-      DOCKER_PASS: ((ci/registry/dockerhub/horlh.password))
-      DOCKER_URL: ((ci/registry/dockerhub/horlh.url))
+      DOCKER_HUB_PROXY: ((dockerhub-proxy))
     config:
       platform: linux
       inputs:
       - name: creds
       - name: repo
+      caches:
+      - path: image-cache
       run:
         path: execute
         args:
@@ -80,10 +80,96 @@ jobs:
           set -u
           set -o pipefail
 
+          # TODO move to image
+          apt-get -y update
+          apt-get -y install pigz
+
           source creds/env.inc.sh
 
           # TODO: remove
-          docker login "${DOCKER_URL}" -u "${DOCKER_USER}" --password-stdin <<< "${DOCKER_PASS}"
+          # docker login "${DOCKER_URL}" -u "${DOCKER_USER}" --password-stdin <<< "${DOCKER_PASS}"
 
+          preheatFromDockerfiles() {
+            local dir="${1:-.}"
+            local orgImg proxyImg
+            local proxy="${DOCKER_HUB_PROXY?}"
+
+            while read orgImg ; do
+              if grep -q '/' <<< "$orgImg" ; then
+                proxyImg="${proxy}/${orgImg}"
+              else
+                proxyImg="${proxy}/library/${orgImg}"
+              fi
+
+              docker pull "$proxyImg" || {
+                echo >&2 "Could not pull '$proxyImg', skipping"
+                continue
+              }
+
+              docker tag "$proxyImg" "$orgImg" || {
+                echo >&2 "Could not retag '$proxyImg' to '$orgImg', skipping"
+                continue
+              }
+            done <<< "$( find "$dir" -type f -iname Dockerfile | xargs -r sed -n 's/^FROM \(.*\)/\1/ip' | sort | uniq )"
+          }
+
+          imageCacheSave() {
+            local dest="$1"
+            local images=()
+            local repo tag id
+
+            while read repo tag id
+            do
+              if [[ "$repo" == '<none>' ]] || [[ "$tag" == '<none>' ]] ; then
+                images+=( "$id" )
+              else
+                images+=( "${repo}:${tag}" )
+              fi
+            done < <( docker image ls -a --format '{{ .Repository }}\t{{ .Tag }}\t{{ .ID }}' )
+
+            docker save "${images[@]}" | pigz > "$dest"
+          }
+
+          imageCacheLoad() {
+            local images="$1"
+
+            [[ -e "$images" ]] || {
+              echo >&2 "'$images' does not exist, not loading cached layers"
+              return
+            }
+
+            # docker load can handle gzipped tarballs
+            docker load -i "$images"
+          }
+
+          main() {
+            taskcat package -s functions/source -z functions/packages
+          }
+
+          runLogged() {
+            local msg="$1" ; shift
+            local rc=0
+
+            echo >&2 "## ---- ${msg}"
+            "$@" || rc=$?
+            echo >&2 "## ----"
+            echo >&2
+
+            return $rc
+          }
+
+          imageCache="${PWD}/image-cache/images.tar.gz"
           cd repo
-          taskcat test run
+
+          runLogged 'load images from cache' \
+            imageCacheLoad "$imageCache" || true
+          runLogged 'preheat docker image cache from Dockerfiles' \
+            preheatFromDockerfiles . || true
+
+          rc=0
+          runLogged 'main task' main || rc=$?
+
+          runLogged 'save images to cache' \
+            imageCacheSave "$imageCache" || true
+
+          exit $rc
