Change payload for cfn-signal
Turns out, the data we send with `--data` is nowhere to be found.

However, data we send via `--reason` is added to the stack event's
status reason.

So sending `--reason "some reason"` and a failure results in a status
reason like:
```
WaitCondition received failed message: 'some reason' for uniqueId: i-06338885b90aa37d9
```

Thus we'll use this to send the last couple of cloud init logs to give
users some context on what went wrong.

Note:
We won't see the newlines in the WebUI, however we see them in the API:
```
: aws cf describe-stack-events --region us-east-1 --stack-name "${VPCStackName}" | jq '.StackEvents[0].ResourceStatusReason' -r
WaitCondition received failed message: '
>>> package(namespace-provisioner) failed to reconcile (Reconciling), waiting for reconcile
>>> package(scanning) failed to reconcile (Reconciling), waiting for reconcile
>>> package(service-bindings) failed to reconcile (Reconciling), waiting for reconcile
>>> package(tap) failed to reconcile (Reconciling), waiting for reconcile
>>> package(tap) failed to reconcile (Reconciling), waiting for reconcile
>>> package(tap-auth) failed to reconcile (Reconciling), waiting for reconcile
>>> package(tap-telemetry) failed to reconcile (Reconciling), waiting for reconcile
>>> package(tekton-pipelines) failed to reconcile (Reconciling), waiting for reconcile
Terminated
' for uniqueId: i-0a7ca048976149f86
:
```

diff --git a/templates/aws-tap-entrypoint-existing-vpc.template.yaml b/templates/aws-tap-entrypoint-existing-vpc.template.yaml
--- a/templates/aws-tap-entrypoint-existing-vpc.template.yaml
+++ b/templates/aws-tap-entrypoint-existing-vpc.template.yaml
@@ -2451,23 +2451,18 @@ Resources:
 
               local rc="${!1:-42}"
               local handleURL="${!2:-${CloudInitHandle}}"
-              local args=(
-                --region "${!AWS_REGION}"
-                --exit-code "$rc"
-              )
+              local reason='installation succeeded'
+              local ctxLines=10
 
-              if (( rc == 0 )) ; then
-                args+=(
-                  --reason "tap-install: succeeded"
-                )
-              else
-                args+=(
-                  --reason "tap-install: failed"
-                  --data "[...] $( tail -n 6 /var/log/cloud-init-output.log )"
-                )
-              fi
+              (( rc != 0 )) && {
+                local nl=$'\n'
+                # We don't care about the last 3 lines of the log, because
+                # that's logging the cfnSignal itself.
+                reason="${!nl}$( tail -n $(( ctxLines + 3 )) /var/log/cloud-init-output.log | head -n -3 )${!nl}"
+              }
 
-              cfn-signal "${!args[@]}" "$handleURL" || echo >&2 'could not run cfn-signal'
+              cfn-signal --region "${!AWS_REGION}" --exit-code "$rc" --reason "$reason" "$handleURL" \
+                || echo >&2 'could not run cfn-signal'
             }
             export -f cfnSignal
             trap 'cfnSignal $?' ERR
